export * as pico from "https://deno.land/std@0.157.0/fmt/colors.ts";
export { default as browserslist } from "https://esm.sh/browserslist@4.21.4/index.js";
export { default as parser } from "https://deno.land/x/postcss_value_parser@4.2.0/mod.js";
import caniuse_lite from "../data/caniuse-lite.js";

export { default as range } from "https://esm.sh/normalize-range@0.1.2/index.js";
export { default as FractionJs } from "https://esm.sh/fraction.js@4.2.0/fraction.js";

import postcss from "https://deno.land/x/postcss@8.4.16/mod.js";
const { list, parse } = postcss;
export { list, parse };

export const feature = caniuse_lite.feature;
export const unpack = feature.unpack;
export const agents = caniuse_lite.agents;

export { default as featureQueries } from "../data/features/css-featurequeries.js";
export { default as prefixBorderRadius } from "../data/features/border-radius.js";
export { default as prefixBoxshadow } from "../data/features/css-boxshadow.js";
export { default as prefixAnimation } from "../data/features/css-animation.js";
export { default as prefixTransition } from "../data/features/css-transitions.js";
export { default as prefixTransform2d } from "../data/features/transforms2d.js";
export { default as prefixTransforms3d } from "../data/features/transforms3d.js";
export { default as prefixGradients } from "../data/features/css-gradients.js";
export { default as prefixBoxsizing } from "../data/features/css3-boxsizing.js";
export { default as prefixFilters } from "../data/features/css-filters.js";
export { default as prefixFilterFunction } from "../data/features/css-filter-function.js";
export { default as prefixBackdrop } from "../data/features/css-backdrop-filter.js";
export { default as prefixElementFunction } from "../data/features/css-element-function.js";
export { default as prefixMulticolumns } from "../data/features/multicolumn.js";
export { default as prefixUserSelect } from "../data/features/user-select-none.js";
export { default as prefixFlexbox } from "../data/features/flexbox.js";
export { default as prefixCalc } from "../data/features/calc.js";
export { default as prefixBackgroundOptions } from "../data/features/background-img-opts.js";
export { default as prefixBackgroundClipText } from "../data/features/background-clip-text.js";
export { default as prefixFontFeature } from "../data/features/font-feature.js";
export { default as prefixFontKerning } from "../data/features/font-kerning.js";
export { default as prefixBorderImage } from "../data/features/border-image.js";
export { default as prefixSelection } from "../data/features/css-selection.js";
export { default as prefixPlaceholder } from "../data/features/css-placeholder.js";
export { default as prefixPlaceholderShown } from "../data/features/css-placeholder-shown.js";
export { default as prefixHyphens } from "../data/features/css-hyphens.js";
export { default as prefixFullscreen } from "../data/features/fullscreen.js";
export { default as prefixTabsize } from "../data/features/css3-tabsize.js";
export { default as prefixIntrinsic } from "../data/features/intrinsic-width.js";
export { default as prefixCursorsNewer } from "../data/features/css3-cursors-newer.js";
export { default as prefixCursorsGrab } from "../data/features/css3-cursors-grab.js";
export { default as prefixSticky } from "../data/features/css-sticky.js";
export { default as prefixPointer } from "../data/features/pointer.js";
export { default as prefixDecoration } from "../data/features/text-decoration.js";
export { default as prefixTextSizeAdjust } from "../data/features/text-size-adjust.js";
export { default as prefixCssMasks } from "../data/features/css-masks.js";
export { default as prefixClipPath } from "../data/features/css-clip-path.js";
export { default as prefixBoxdecoration } from "../data/features/css-boxdecorationbreak.js";
export { default as prefixObjectFit } from "../data/features/object-fit.js";
export { default as prefixShapes } from "../data/features/css-shapes.js";
export { default as prefixTextOverflow } from "../data/features/text-overflow.js";
export { default as prefixDeviceadaptation } from "../data/features/css-deviceadaptation.js";
export { default as prefixResolut } from "../data/features/css-media-resolution.js";
export { default as prefixTextAlignLast } from "../data/features/css-text-align-last.js";
export { default as prefixCrispedges } from "../data/features/css-crisp-edges.js";
export { default as prefixLogicalProps } from "../data/features/css-logical-props.js";
export { default as prefixAppearance } from "../data/features/css-appearance.js";
export { default as prefixSnappoints } from "../data/features/css-snappoints.js";
export { default as prefixRegions } from "../data/features/css-regions.js";
export { default as prefixImageSet } from "../data/features/css-image-set.js";
export { default as prefixWritingMode } from "../data/features/css-writing-mode.js";
export { default as prefixCrossFade } from "../data/features/css-cross-fade.js";
export { default as prefixReadOnly } from "../data/features/css-read-only-write.js";
export { default as prefixTextEmphasis } from "../data/features/text-emphasis.js";
export { default as prefixGrid } from "../data/features/css-grid.js";
export { default as prefixTextSpacing } from "../data/features/css-text-spacing.js";
export { default as prefixAnyLink } from "../data/features/css-any-link.js";
export { default as prefixOverscroll } from "../data/features/css-overscroll-behavior.js";
export { default as prefixColorAdjust } from "../data/features/css-color-adjust.js";
export { default as prefixTextOrientation } from "../data/features/css-text-orientation.js";
export { default as prefixAutofill } from "../data/features/css-autofill.js";
export { default as prefixFileSelectorButton } from "../data/features/css-file-selector-button.js";
export { default as prefixStretch } from "../data/features/css-width-stretch.js";
export { default as prefixPrintAdjust } from "../data/features/css-print-color-adjust.js";
export { default as prefixDecorationShorthand } from "../data/features/mdn-text-decoration-shorthand.js";
export { default as prefixDecorationColor } from "../data/features/mdn-text-decoration-color.js";
export { default as prefixDecorationLine } from "../data/features/mdn-text-decoration-line.js";
export { default as prefixDecorationStyle } from "../data/features/mdn-text-decoration-style.js";
export { default as bidiIsolate } from "../data/features/mdn-css-unicode-bidi-isolate.js";
export { default as bidiPlaintext } from "../data/features/mdn-css-unicode-bidi-plaintext.js";
export { default as bidiOverride } from "../data/features/mdn-css-unicode-bidi-isolate-override.js";
