export { default as browserslist } from "https://jspm.dev/browserslist@4.16.6";
export { default as parser } from "https://deno.land/x/postcss_value_parser@v4.1.0/mod.js";
import caniuse_lite from "https://jspm.dev/caniuse-lite@1.0.30001223";

export { default as featureQueries } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-featurequeries.js";
export { default as range } from "https://jspm.dev/normalize-range@0.1.2";
export { default as FractionJs } from "https://jspm.dev/fraction.js@4.0.13";

import postcss from "https://deno.land/x/postcss@8.3.0.1/mod.js";
const { list, Fraction, parse } = postcss;
export { list, parse };

export const feature = caniuse_lite.feature;
export const unpack = feature.unpack;
export const agents = caniuse_lite.agents;
export const colorette = {};

export { default as prefixBorderRadius } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/border-radius";
export { default as prefixBoxshadow } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-boxshadow";
export { default as prefixAnimation } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-animation";
export { default as prefixTransition } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-transitions";
export { default as prefixTransform2d } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/transforms2d";
export { default as prefixTransforms3d } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/transforms3d";
export { default as prefixGradients } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-gradients";
export { default as prefixBoxsizing } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css3-boxsizing";
export { default as prefixFilters } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-filters";
export { default as prefixFilterFunction } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-filter-function";
export { default as prefixBackdrop } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-backdrop-filter";
export { default as prefixElementFunction } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-element-function";
export { default as prefixMulticolumns } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/multicolumn";
export { default as prefixUserSelect } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/user-select-none";
export { default as prefixFlexbox } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/flexbox";
export { default as prefixCalc } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/calc";
export { default as prefixBackgroundOptions } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/background-img-opts";
export { default as prefixBackgroundClipText } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/background-clip-text";
export { default as prefixFontFeature } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/font-feature";
export { default as prefixFontKerning } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/font-kerning";
export { default as prefixBorderImage } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/border-image";
export { default as prefixSelection } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-selection";
export { default as prefixPlaceholder } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-placeholder";
export { default as prefixPlaceholderShown } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-placeholder-shown";
export { default as prefixHyphens } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-hyphens";
export { default as prefixFullscreen } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/fullscreen";
export { default as prefixTabsize } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css3-tabsize";
export { default as prefixIntrinsic } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/intrinsic-width";
export { default as prefixCursorsNewer } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css3-cursors-newer";
export { default as prefixCursorsGrab } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css3-cursors-grab";
export { default as prefixSticky } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-sticky";
export { default as prefixPointer } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/pointer";
export { default as prefixDecoration } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/text-decoration";
export { default as prefixTextSizeAdjust } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/text-size-adjust";
export { default as prefixCssMasks } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-masks";
export { default as prefixClipPath } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-clip-path";
export { default as prefixBoxdecoration } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-boxdecorationbreak";
export { default as prefixObjectFit } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/object-fit";
export { default as prefixShapes } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-shapes";
export { default as prefixTextOverflow } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/text-overflow";
export { default as prefixDeviceadaptation } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-deviceadaptation";
export { default as prefixResolut } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-media-resolution";
export { default as prefixTextAlignLast } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-text-align-last";
export { default as prefixCrispedges } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-crisp-edges";
export { default as prefixLogicalProps } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-logical-props";
export { default as prefixAppearance } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-appearance";
export { default as prefixSnappoints } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-snappoints";
export { default as prefixRegions } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-regions";
export { default as prefixImageSet } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-image-set";
export { default as prefixWritingMode } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-writing-mode";
export { default as prefixCrossFade } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-cross-fade";
export { default as prefixReadOnly } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-read-only-write";
export { default as prefixTextEmphasis } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/text-emphasis";
export { default as prefixGrid } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-grid";
export { default as prefixTextSpacing } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-text-spacing";
export { default as prefixAnyLink } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-any-link";
export { default as prefixBidi } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-unicode-bidi";
export { default as prefixOverscroll } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-overscroll-behavior";
export { default as prefixColorAdjust } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-color-adjust";
export { default as prefixTextOrientation } from "https://jspm.dev/caniuse-lite@1.0.30001223/data/features/css-text-orientation";
